#!/bin/sh
if [ "$1" ]; then
  manpage=`man -w $@`
else
  read line
  section=`expr "$line" : '.*(\(.*\))'`
  if [ "$section" ]; then
  	manpage=`expr "$line" : '\(.*\)('`
        manpage=`man -s $section -w "$manpage"`
  else
        manpage=`man -w "$line"`
  fi
fi
[ "$manpage" ] || exit 0

tmp=`mktemp -t TextMate`
trap 'rm -f "$tmp"' EXIT

(
  echo $manpage | fmt -c -w 78;
  man "$manpage" \
  | col -bx \
  | perl -pe '
      print "_"x (length($_)-1),"\n" if /^[A-Z](?:(?:\S+\s\S+)+|\S+)$/;
      END {print "__"}
  '
) > "$tmp"

"$TM_MATE" < "$tmp" --name "$(basename $manpage .gz).man" --no-wait
